/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards.index'
import { Route as ErrosIndexRouteImport } from './routes/erros.index'
import { Route as ConteudoIndexRouteImport } from './routes/conteudo.index'
import { Route as CalendarioIndexRouteImport } from './routes/calendario.index'
import { Route as FlashcardsNovoBaralhoRouteImport } from './routes/flashcards.novo-baralho'
import { Route as ConteudoNovaDisciplinaRouteImport } from './routes/conteudo.nova-disciplina'
import { Route as CalendarioRegistrarRouteImport } from './routes/calendario.registrar'
import { Route as ErrosDisciplinaNomeRouteImport } from './routes/erros.disciplina.$nome'
import { Route as FlashcardsBaralhoIdIndexRouteImport } from './routes/flashcards.baralho.$id.index'
import { Route as ConteudoDisciplinaNomeIndexRouteImport } from './routes/conteudo.disciplina.$nome.index'
import { Route as FlashcardsFlashcardIdEditarRouteImport } from './routes/flashcards.flashcard.$id.editar'
import { Route as FlashcardsBaralhoIdNovoFlashcardRouteImport } from './routes/flashcards.baralho.$id.novo-flashcard'
import { Route as ConteudoDisciplinaNomeNovoTopicoRouteImport } from './routes/conteudo.disciplina.$nome.novo-topico'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosIndexRoute = ErrosIndexRouteImport.update({
  id: '/erros/',
  path: '/erros/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoIndexRoute = ConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioIndexRoute = CalendarioIndexRouteImport.update({
  id: '/calendario/',
  path: '/calendario/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsNovoBaralhoRoute = FlashcardsNovoBaralhoRouteImport.update({
  id: '/flashcards/novo-baralho',
  path: '/flashcards/novo-baralho',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoNovaDisciplinaRoute = ConteudoNovaDisciplinaRouteImport.update({
  id: '/conteudo/nova-disciplina',
  path: '/conteudo/nova-disciplina',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRegistrarRoute = CalendarioRegistrarRouteImport.update({
  id: '/calendario/registrar',
  path: '/calendario/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosDisciplinaNomeRoute = ErrosDisciplinaNomeRouteImport.update({
  id: '/erros/disciplina/$nome',
  path: '/erros/disciplina/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsBaralhoIdIndexRoute =
  FlashcardsBaralhoIdIndexRouteImport.update({
    id: '/flashcards/baralho/$id/',
    path: '/flashcards/baralho/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudoDisciplinaNomeIndexRoute =
  ConteudoDisciplinaNomeIndexRouteImport.update({
    id: '/conteudo/disciplina/$nome/',
    path: '/conteudo/disciplina/$nome/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlashcardsFlashcardIdEditarRoute =
  FlashcardsFlashcardIdEditarRouteImport.update({
    id: '/flashcards/flashcard/$id/editar',
    path: '/flashcards/flashcard/$id/editar',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlashcardsBaralhoIdNovoFlashcardRoute =
  FlashcardsBaralhoIdNovoFlashcardRouteImport.update({
    id: '/flashcards/baralho/$id/novo-flashcard',
    path: '/flashcards/baralho/$id/novo-flashcard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudoDisciplinaNomeNovoTopicoRoute =
  ConteudoDisciplinaNomeNovoTopicoRouteImport.update({
    id: '/conteudo/disciplina/$nome/novo-topico',
    path: '/conteudo/disciplina/$nome/novo-topico',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desempenho': typeof DesempenhoRoute
  '/login': typeof LoginRoute
  '/calendario/registrar': typeof CalendarioRegistrarRoute
  '/conteudo/nova-disciplina': typeof ConteudoNovaDisciplinaRoute
  '/flashcards/novo-baralho': typeof FlashcardsNovoBaralhoRoute
  '/calendario/': typeof CalendarioIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/erros/': typeof ErrosIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/erros/disciplina/$nome': typeof ErrosDisciplinaNomeRoute
  '/conteudo/disciplina/$nome/novo-topico': typeof ConteudoDisciplinaNomeNovoTopicoRoute
  '/flashcards/baralho/$id/novo-flashcard': typeof FlashcardsBaralhoIdNovoFlashcardRoute
  '/flashcards/flashcard/$id/editar': typeof FlashcardsFlashcardIdEditarRoute
  '/conteudo/disciplina/$nome/': typeof ConteudoDisciplinaNomeIndexRoute
  '/flashcards/baralho/$id/': typeof FlashcardsBaralhoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desempenho': typeof DesempenhoRoute
  '/login': typeof LoginRoute
  '/calendario/registrar': typeof CalendarioRegistrarRoute
  '/conteudo/nova-disciplina': typeof ConteudoNovaDisciplinaRoute
  '/flashcards/novo-baralho': typeof FlashcardsNovoBaralhoRoute
  '/calendario': typeof CalendarioIndexRoute
  '/conteudo': typeof ConteudoIndexRoute
  '/erros': typeof ErrosIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
  '/erros/disciplina/$nome': typeof ErrosDisciplinaNomeRoute
  '/conteudo/disciplina/$nome/novo-topico': typeof ConteudoDisciplinaNomeNovoTopicoRoute
  '/flashcards/baralho/$id/novo-flashcard': typeof FlashcardsBaralhoIdNovoFlashcardRoute
  '/flashcards/flashcard/$id/editar': typeof FlashcardsFlashcardIdEditarRoute
  '/conteudo/disciplina/$nome': typeof ConteudoDisciplinaNomeIndexRoute
  '/flashcards/baralho/$id': typeof FlashcardsBaralhoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desempenho': typeof DesempenhoRoute
  '/login': typeof LoginRoute
  '/calendario/registrar': typeof CalendarioRegistrarRoute
  '/conteudo/nova-disciplina': typeof ConteudoNovaDisciplinaRoute
  '/flashcards/novo-baralho': typeof FlashcardsNovoBaralhoRoute
  '/calendario/': typeof CalendarioIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/erros/': typeof ErrosIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/erros/disciplina/$nome': typeof ErrosDisciplinaNomeRoute
  '/conteudo/disciplina/$nome/novo-topico': typeof ConteudoDisciplinaNomeNovoTopicoRoute
  '/flashcards/baralho/$id/novo-flashcard': typeof FlashcardsBaralhoIdNovoFlashcardRoute
  '/flashcards/flashcard/$id/editar': typeof FlashcardsFlashcardIdEditarRoute
  '/conteudo/disciplina/$nome/': typeof ConteudoDisciplinaNomeIndexRoute
  '/flashcards/baralho/$id/': typeof FlashcardsBaralhoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/desempenho'
    | '/login'
    | '/calendario/registrar'
    | '/conteudo/nova-disciplina'
    | '/flashcards/novo-baralho'
    | '/calendario/'
    | '/conteudo/'
    | '/erros/'
    | '/flashcards/'
    | '/erros/disciplina/$nome'
    | '/conteudo/disciplina/$nome/novo-topico'
    | '/flashcards/baralho/$id/novo-flashcard'
    | '/flashcards/flashcard/$id/editar'
    | '/conteudo/disciplina/$nome/'
    | '/flashcards/baralho/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/desempenho'
    | '/login'
    | '/calendario/registrar'
    | '/conteudo/nova-disciplina'
    | '/flashcards/novo-baralho'
    | '/calendario'
    | '/conteudo'
    | '/erros'
    | '/flashcards'
    | '/erros/disciplina/$nome'
    | '/conteudo/disciplina/$nome/novo-topico'
    | '/flashcards/baralho/$id/novo-flashcard'
    | '/flashcards/flashcard/$id/editar'
    | '/conteudo/disciplina/$nome'
    | '/flashcards/baralho/$id'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/desempenho'
    | '/login'
    | '/calendario/registrar'
    | '/conteudo/nova-disciplina'
    | '/flashcards/novo-baralho'
    | '/calendario/'
    | '/conteudo/'
    | '/erros/'
    | '/flashcards/'
    | '/erros/disciplina/$nome'
    | '/conteudo/disciplina/$nome/novo-topico'
    | '/flashcards/baralho/$id/novo-flashcard'
    | '/flashcards/flashcard/$id/editar'
    | '/conteudo/disciplina/$nome/'
    | '/flashcards/baralho/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DesempenhoRoute: typeof DesempenhoRoute
  LoginRoute: typeof LoginRoute
  CalendarioRegistrarRoute: typeof CalendarioRegistrarRoute
  ConteudoNovaDisciplinaRoute: typeof ConteudoNovaDisciplinaRoute
  FlashcardsNovoBaralhoRoute: typeof FlashcardsNovoBaralhoRoute
  CalendarioIndexRoute: typeof CalendarioIndexRoute
  ConteudoIndexRoute: typeof ConteudoIndexRoute
  ErrosIndexRoute: typeof ErrosIndexRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
  ErrosDisciplinaNomeRoute: typeof ErrosDisciplinaNomeRoute
  ConteudoDisciplinaNomeNovoTopicoRoute: typeof ConteudoDisciplinaNomeNovoTopicoRoute
  FlashcardsBaralhoIdNovoFlashcardRoute: typeof FlashcardsBaralhoIdNovoFlashcardRoute
  FlashcardsFlashcardIdEditarRoute: typeof FlashcardsFlashcardIdEditarRoute
  ConteudoDisciplinaNomeIndexRoute: typeof ConteudoDisciplinaNomeIndexRoute
  FlashcardsBaralhoIdIndexRoute: typeof FlashcardsBaralhoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros/': {
      id: '/erros/'
      path: '/erros'
      fullPath: '/erros/'
      preLoaderRoute: typeof ErrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/': {
      id: '/conteudo/'
      path: '/conteudo'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof ConteudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario/': {
      id: '/calendario/'
      path: '/calendario'
      fullPath: '/calendario/'
      preLoaderRoute: typeof CalendarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/novo-baralho': {
      id: '/flashcards/novo-baralho'
      path: '/flashcards/novo-baralho'
      fullPath: '/flashcards/novo-baralho'
      preLoaderRoute: typeof FlashcardsNovoBaralhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/nova-disciplina': {
      id: '/conteudo/nova-disciplina'
      path: '/conteudo/nova-disciplina'
      fullPath: '/conteudo/nova-disciplina'
      preLoaderRoute: typeof ConteudoNovaDisciplinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario/registrar': {
      id: '/calendario/registrar'
      path: '/calendario/registrar'
      fullPath: '/calendario/registrar'
      preLoaderRoute: typeof CalendarioRegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros/disciplina/$nome': {
      id: '/erros/disciplina/$nome'
      path: '/erros/disciplina/$nome'
      fullPath: '/erros/disciplina/$nome'
      preLoaderRoute: typeof ErrosDisciplinaNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/baralho/$id/': {
      id: '/flashcards/baralho/$id/'
      path: '/flashcards/baralho/$id'
      fullPath: '/flashcards/baralho/$id/'
      preLoaderRoute: typeof FlashcardsBaralhoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/disciplina/$nome/': {
      id: '/conteudo/disciplina/$nome/'
      path: '/conteudo/disciplina/$nome'
      fullPath: '/conteudo/disciplina/$nome/'
      preLoaderRoute: typeof ConteudoDisciplinaNomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/flashcard/$id/editar': {
      id: '/flashcards/flashcard/$id/editar'
      path: '/flashcards/flashcard/$id/editar'
      fullPath: '/flashcards/flashcard/$id/editar'
      preLoaderRoute: typeof FlashcardsFlashcardIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/baralho/$id/novo-flashcard': {
      id: '/flashcards/baralho/$id/novo-flashcard'
      path: '/flashcards/baralho/$id/novo-flashcard'
      fullPath: '/flashcards/baralho/$id/novo-flashcard'
      preLoaderRoute: typeof FlashcardsBaralhoIdNovoFlashcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/disciplina/$nome/novo-topico': {
      id: '/conteudo/disciplina/$nome/novo-topico'
      path: '/conteudo/disciplina/$nome/novo-topico'
      fullPath: '/conteudo/disciplina/$nome/novo-topico'
      preLoaderRoute: typeof ConteudoDisciplinaNomeNovoTopicoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DesempenhoRoute: DesempenhoRoute,
  LoginRoute: LoginRoute,
  CalendarioRegistrarRoute: CalendarioRegistrarRoute,
  ConteudoNovaDisciplinaRoute: ConteudoNovaDisciplinaRoute,
  FlashcardsNovoBaralhoRoute: FlashcardsNovoBaralhoRoute,
  CalendarioIndexRoute: CalendarioIndexRoute,
  ConteudoIndexRoute: ConteudoIndexRoute,
  ErrosIndexRoute: ErrosIndexRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
  ErrosDisciplinaNomeRoute: ErrosDisciplinaNomeRoute,
  ConteudoDisciplinaNomeNovoTopicoRoute: ConteudoDisciplinaNomeNovoTopicoRoute,
  FlashcardsBaralhoIdNovoFlashcardRoute: FlashcardsBaralhoIdNovoFlashcardRoute,
  FlashcardsFlashcardIdEditarRoute: FlashcardsFlashcardIdEditarRoute,
  ConteudoDisciplinaNomeIndexRoute: ConteudoDisciplinaNomeIndexRoute,
  FlashcardsBaralhoIdIndexRoute: FlashcardsBaralhoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
