/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as ErrosRouteImport } from './routes/erros'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlashcardsNovoBaralhoRouteImport } from './routes/flashcards.novo-baralho'
import { Route as FlashcardsBaralhoIdRouteImport } from './routes/flashcards.baralho.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosRoute = ErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsNovoBaralhoRoute = FlashcardsNovoBaralhoRouteImport.update({
  id: '/novo-baralho',
  path: '/novo-baralho',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsBaralhoIdRoute = FlashcardsBaralhoIdRouteImport.update({
  id: '/baralho/$id',
  path: '/baralho/$id',
  getParentRoute: () => FlashcardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/desempenho': typeof DesempenhoRoute
  '/erros': typeof ErrosRoute
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/login': typeof LoginRoute
  '/flashcards/novo-baralho': typeof FlashcardsNovoBaralhoRoute
  '/flashcards/baralho/$id': typeof FlashcardsBaralhoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/desempenho': typeof DesempenhoRoute
  '/erros': typeof ErrosRoute
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/login': typeof LoginRoute
  '/flashcards/novo-baralho': typeof FlashcardsNovoBaralhoRoute
  '/flashcards/baralho/$id': typeof FlashcardsBaralhoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/desempenho': typeof DesempenhoRoute
  '/erros': typeof ErrosRoute
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/login': typeof LoginRoute
  '/flashcards/novo-baralho': typeof FlashcardsNovoBaralhoRoute
  '/flashcards/baralho/$id': typeof FlashcardsBaralhoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/conteudo'
    | '/desempenho'
    | '/erros'
    | '/flashcards'
    | '/login'
    | '/flashcards/novo-baralho'
    | '/flashcards/baralho/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/conteudo'
    | '/desempenho'
    | '/erros'
    | '/flashcards'
    | '/login'
    | '/flashcards/novo-baralho'
    | '/flashcards/baralho/$id'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/conteudo'
    | '/desempenho'
    | '/erros'
    | '/flashcards'
    | '/login'
    | '/flashcards/novo-baralho'
    | '/flashcards/baralho/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConteudoRoute: typeof ConteudoRoute
  DesempenhoRoute: typeof DesempenhoRoute
  ErrosRoute: typeof ErrosRoute
  FlashcardsRoute: typeof FlashcardsRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros': {
      id: '/erros'
      path: '/erros'
      fullPath: '/erros'
      preLoaderRoute: typeof ErrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/novo-baralho': {
      id: '/flashcards/novo-baralho'
      path: '/novo-baralho'
      fullPath: '/flashcards/novo-baralho'
      preLoaderRoute: typeof FlashcardsNovoBaralhoRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/baralho/$id': {
      id: '/flashcards/baralho/$id'
      path: '/baralho/$id'
      fullPath: '/flashcards/baralho/$id'
      preLoaderRoute: typeof FlashcardsBaralhoIdRouteImport
      parentRoute: typeof FlashcardsRoute
    }
  }
}

interface FlashcardsRouteChildren {
  FlashcardsNovoBaralhoRoute: typeof FlashcardsNovoBaralhoRoute
  FlashcardsBaralhoIdRoute: typeof FlashcardsBaralhoIdRoute
}

const FlashcardsRouteChildren: FlashcardsRouteChildren = {
  FlashcardsNovoBaralhoRoute: FlashcardsNovoBaralhoRoute,
  FlashcardsBaralhoIdRoute: FlashcardsBaralhoIdRoute,
}

const FlashcardsRouteWithChildren = FlashcardsRoute._addFileChildren(
  FlashcardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConteudoRoute: ConteudoRoute,
  DesempenhoRoute: DesempenhoRoute,
  ErrosRoute: ErrosRoute,
  FlashcardsRoute: FlashcardsRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
